// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uexbhpgvqgauwowcswwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVleGJocGd2cWdhdXdvd2Nzd3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTAyODcsImV4cCI6MjA2MzU2NjI4N30.8dKdwxKTTey-l-c7mb5rWSGMqbHW9QDY-rJ1Fl2sOLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);